hypo: 
  layout:
    activated: true
      
    templates:
      # except default treat at the end the templates are verify by order:
      # - annotations
      # - configurations
      # - default
      default: HypoTestBundle::layout.html.twig
      global:
        template: HypoTestBundle::layout.html.twig
        #indicated as namespaced_class::function
        targets: []
    parameters: ~

    # bloc are parsed
    blocs:
      menu: HypoTestBundle::menu.html.twig
    
  fileserver:
    testfile:
      repository: HypoTestBundle:File #The repository name
      availability: false #false or a period in second